//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sol_CienciasMedicWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL08_TALLERES
    {
        public int TALL_ID { get; set; }
        public string TALL_NAME { get; set; }
        public Nullable<decimal> TALL_PRICE { get; set; }
        public Nullable<int> TALL_EST_REG { get; set; }
        public Nullable<System.DateTime> TALL_FEC_REG { get; set; }
        public string TALL_USU_REG { get; set; }
    }
}
