//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sol_CienciasMedicWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL04_MENSAJES
    {
        public int MSJ_ID { get; set; }
        public string MSJ_NOMBRES { get; set; }
        public string MSJ_EMAIL { get; set; }
        public string MSJ_TITULO { get; set; }
        public string MSJ_CONTENIDO { get; set; }
        public Nullable<int> MSJ_EST_REG { get; set; }
        public Nullable<System.DateTime> MSJ_FEC_REG { get; set; }
        public string MSJ_USU_REG { get; set; }
    }
}
