//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sol_CienciasMedicWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL07_PAQUETES
    {
        public int PAQ_ID { get; set; }
        public string PAQ_NOMBRE { get; set; }
        public Nullable<decimal> PAQ_PRICE { get; set; }
        public Nullable<int> PAQ_EST_REG { get; set; }
        public Nullable<int> CUR_ID { get; set; }
        public Nullable<System.DateTime> PAQ_FEC_REG { get; set; }
        public string PAQ_USU_REG { get; set; }
    }
}
