//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sol_CienciasMedicWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL01_INSCRIPCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL01_INSCRIPCIONES()
        {
            this.TBL03_INS_CURSO = new HashSet<TBL03_INS_CURSO>();
        }
    
        public int INS_ID { get; set; }
        public string INS_NOMBRES { get; set; }
        public string INS_APELLIDOS { get; set; }
        public string INS_DNI { get; set; }
        public string INS_CELL { get; set; }
        public string INS_EMAIL { get; set; }
        public Nullable<int> INS_EST_REG { get; set; }
        public Nullable<System.DateTime> INS_FEC_REG { get; set; }
        public string INS_USU_REG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL03_INS_CURSO> TBL03_INS_CURSO { get; set; }
    }
}
