//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sol_CienciasMedicWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL03_INS_CURSO
    {
        public int INS_ID { get; set; }
        public int CUR_ID { get; set; }
        public Nullable<int> EST_REG { get; set; }
        public Nullable<System.DateTime> FEC_INSC { get; set; }
        public string USU_REG { get; set; }
    
        public virtual TBL01_INSCRIPCIONES TBL01_INSCRIPCIONES { get; set; }
        public virtual TBL02_CURSOS TBL02_CURSOS { get; set; }
    }
}
